# Where to save downloaded files. The script tries these destinations in order until one works.
download_destinations:
  # SMB share (omit if not needed)
  - type: smb
    server: "192.168.50.5" # IP or hostname of your SMB server
    share: "Media" # Name of the SMB share
    path: "XXX" # Folder within the share to save videos
    username: "SMB_User" # SMB username
    password: "SMB_Password" # SMB password
    temporary_storage: "/tmp/smutscrape" # Local temp folder for downloads before SMB upload (default: /tmp/smutscrape)
    permissions: # Optional: Set file ownership and permissions
      uid: 1000 # User ID (numeric)
      gid: 3003 # Group ID (numeric, e.g., media group)
      mode: "750" # Permissions (e.g., rwxr-x---)

  # WebDAV share (omit if not needed)
  - type: webdav
    url: "https://example.com/webdav" # Full URL to your WebDAV server
    path: "videos" # Folder within WebDAV to save videos
    username: "user" # WebDAV username
    password: "password" # WebDAV password

  # Local filesystem (default fallback)
  - type: local
    path: "~/.xxx" # Local folder to save videos (e.g., /home/user/.xxx)

# Whether to overwrite existing files (default: false preserves files)
overwrite_files: false

# Allows the creation of .nfo files holding scraped metadata
make_nfo: true

# Terms to skip during scraping (case-insensitive, applied to all metadata fields
ignored:
  - "JOI"
  - "Virtual Sex"
  - "Scat"

# Selenium configuration for sites requiring JavaScript or M3U8 streams. Leave it set to "local" and the rest commented out to let webdriver-manager handle everything, override with the paths to your Chrome and chromedriver binaries, or use a remote Selenium host.
selenium:
  mode: "local" # "local" or "remote" (e.g., Docker)
  # chromedriver_path: "/usr/bin/chromedriver"  # Optional: Path to ChromeDriver; omit to use webdriver-manager
  # chrome_binary: "/usr/lib/chromium/chromium"  # Optional: Path to Chrome binary (e.g., for Debian)
  # host: "127.0.0.1"                  # Remote Selenium host (if mode is "remote")
  # port: "4444"                       # Remote Selenium port (if mode is "remote")

# VPN settings for anonymous scraping (omit or set enabled: false if not used)
vpn:
  enabled: false # Set to true to enable VPN
  vpn_bin: "/usr/bin/vpn-client" # Path to VPN executable (e.g., /usr/bin/protonvpn-cli)
  start_cmd: "{vpn_bin} connect" # Command to start VPN
  stop_cmd: "{vpn_bin} disconnect" # Command to stop VPN
  new_node_cmd: "{vpn_bin} connect --random" # Command to switch VPN node
  new_node_time: 300 # Seconds between node switches (e.g., 5 minutes)

# ---- Advanced settings below (usually no need to change) ----
# These capitalization override rules ensure that, for example, "jayspov" is converted to "JaysPOV"
case_overrides:
  - "ABDL"
  - "ASMR"
  - "BBW"
  - "BDSM"
  - "BrattySis"
  - "BrutalX"
  - "DILF"
  - "FamilyTherapyXXX"
  - "HD"
  - "JAV"
  - "JOI"
  - "POV"
  - "MILF"
  - "MissaX"
  - "XXX"
  - "3D"
  - "4K"

# These special capitalization override rules apply ONLY to tags--not titles or studios. None are included by default,
# but see the commented out entries for examples based on common tags found on IncestFlix.
tag_case_overrides:
  - "NoneByDefault"
  # - "BBS"
  # - "BS"
  # - "BSS"
  # - "DP"
  # - "FD"
  # - "FDD"
  # - "FDDD"
  # - "FMD"
  # - "FMDD"
  # - "FMDDD"
#  - etc...

# Timing delays to avoid overwhelming sites
sleep:
  between_videos: 3 # Seconds to wait between video downloads
  between_pages: 5 # Seconds to wait between page requests

# File naming conventions
file_naming:
  invalid_chars: '/:*?"<>|''' # Characters to remove from filenames
  extension: ".mp4" # Default file extension

# User-Agent strings for HTTP requests (rotated randomly)
user_agents:
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
  - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0"

# HTTP headers for requests
headers:
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
  Accept-Language: "en-US,en;q=0.5"
  Accept-Encoding: "gzip, deflate, br"
  DNT: "1" # Do Not Track
  Connection: "keep-alive"
  Upgrade-Insecure-Requests: "1"

# Fonts to use for site ascii headers (script randomly selects one from the 3 largest that fit in the terminal) 
fonts:
  - 4max
  - amc_3_lin
  - bolger
  - colossal
  - georgia11
  - georgi16
  - poison
  - roman
  - santa_clara
  - smpoison
  - stellar
  - swan
  - tarty1
  - tarty2
  - tarty4
  - bold_script
  - fancy59
  - fancy134
