# Where to save downloaded files. The script tries these destinations in order until one works.
download_destinations:
  # SMB share (omit if not needed)
  - type:              smb
    server:            "192.168.50.5"               # IP or hostname of your SMB server
    share:             "Media"                      # Name of the SMB share
    path:              "XXX"                        # Folder within the share to save videos
    username:          "SMB_User"                   # SMB username
    password:          "SMB_Password"               # SMB password
    temporary_storage: "/tmp/smutscrape"            # Local temp folder for downloads before SMB upload (default: /tmp/smutscrape)
    permissions:                                    # Optional: Set file ownership and permissions
      uid:             1000                         # User ID (numeric)
      gid:             3003                         # Group ID (numeric, e.g., media group)
      mode:            "750"                        # Permissions (e.g., rwxr-x---)

  # WebDAV share (omit if not needed)
  - type:              webdav
    url:               "https://example.com/webdav" # Full URL to your WebDAV server
    path:              "videos"                     # Folder within WebDAV to save videos
    username:          "user"                       # WebDAV username
    password:          "password"                   # WebDAV password

  # Local filesystem (default fallback)
  - type:              local
    path:              "~/.xxx"                     # Local folder to save videos (e.g., /home/user/.xxx)

# --------------------------------------------------------------------------------

# Terms to skip during scraping (case-insensitive, applied to all metadata fields)
ignored:
  - "JOI"
  - "Virtual Sex"
  - "Scat"

# --------------------------------------------------------------------------------

# Selenium configuration for sites requiring JavaScript or HLS streams
selenium:
  mode:                "local"                      # "local" or "remote" (e.g., Docker)
  # Leave the rest commented out to rely on webdriver-manager, the easiest setup that works for most.
  # If that fails, try specifying the paths to your Chrome binary and chromedriver:
  # chromedriver_path: "/usr/local/bin/chromedriver"
  # chrome_binary:     "/Applications/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"  # for macOS
  # Alternatively, set selenium mode to remote and enter host and port for your headless Selenium,
  # e.g., via `docker run -d -p 4444:4444 --name selenium-chrome selenium/standalone-chrome:latest`
  # host:            "127.0.0.1"
  # port:            "4444"

# --------------------------------------------------------------------------------

# VPN settings for anonymous scraping (omit or set enabled: false if not used)
vpn:
  enabled:             false                        # Set to true to enable VPN
  vpn_bin:             "/usr/bin/vpn-client"        # Path to VPN executable (e.g., /usr/bin/protonvpn-cli)
  start_cmd:           "{vpn_bin} connect"          # Command to start VPN
  stop_cmd:            "{vpn_bin} disconnect"       # Command to stop VPN
  new_node_cmd:        "{vpn_bin} connect --random" # Command to switch VPN node
  new_node_time:       300                          # Seconds between node switches (e.g., 5 minutes)

# --------------------------------------------------------------------------------
# ---- Advanced settings below (usually no need to change) ----
# --------------------------------------------------------------------------------

# These capitalization override rules ensure that, for example, "jayspov" is converted to "JaysPOV"
case_overrides:
  - "ABDL"
  - "ASMR"
  - "BBW"
  - "BDSM"
  - "HD"
  - "JAV"
  - "JOI"
  - "POV"
  - "MILF"
  - "XXX"
  - "3D"
  - "4K"
  # ... you can also include studio names here to retain their correct capitalization, e.g.:
  # - "BrattySis"
  # - "BrutalX"
  # - "FamilyTherapyXXX"
  # - "MissaX"

# These special capitalization override rules apply ONLY to tags--not titles or studios
tag_case_overrides:
  - "NoneByDefault"
  # - "BBS"
  # - "BS"
  # - "BSS"
  # - "DP"
  # - "FD"
  # - "FDD"
  # - "FDDD"
  # - "FMD"
  # - "FMDD"
  # - "FMDDD"
  # - etc...

# --------------------------------------------------------------------------------

# Timing delays to avoid overwhelming sites
sleep:
  between_videos:  3                                # Seconds to wait between video downloads
  between_pages:   5                                # Seconds to wait between page requests

# File naming conventions
file_naming:
  invalid_chars:   '/:*?"<>|'''                     # Characters to remove from filenames
  extension:       ".mp4"                           # Default file extension
  max_chars:       200                              # Maximum filename length

# --------------------------------------------------------------------------------

# User-Agent strings for HTTP requests (rotated randomly)
user_agents:
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"
  - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0"

# HTTP headers for requests
headers:
  Accept:          "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
  Accept-Language: "en-US,en;q=0.5"
  Accept-Encoding: "gzip, deflate, br"
  DNT:             "1"                              # Do Not Track
  Connection:      "keep-alive"
  Upgrade-Insecure-Requests: "1"

# --------------------------------------------------------------------------------

# Fonts to use for site ascii headers (script selects the largest from this list that will fit in terminal)
fonts:
  - tarty1
  - tarty2
  - tarty8
  - bold_script
  - fancy59
