#!/usr/bin/env python3
"""
extract_cookies.py
==================
Extracts cookies from your browser and writes a Netscape-format cookies.txt
that yt-dlp / smutscrape can consume via the `cookies_file` config key.

This script uses yt-dlp's own --cookies-from-browser flag, which correctly
handles Windows 10/11 Chrome DPAPI encryption, macOS Keychain, and Linux
secret-service — no extra Python packages required.

Usage
-----
    # Windows (run from the repo folder, Chrome can be open):
    python extract_cookies.py
    python extract_cookies.py --output C:\\Users\\You\\smutscrape-cookies.txt
    python extract_cookies.py --browser edge

    # Linux / macOS:
    python extract_cookies.py --browser firefox

Requirements
------------
    yt-dlp must be installed and on PATH:  pip install -U yt-dlp

Notes
-----
- The script uses a throwaway yt-dlp invocation against a known lightweight
  URL (xhamster's homepage) just to trigger cookie extraction.  The page is
  never actually downloaded.
- On Windows, Chrome does NOT need to be closed first.
- The output file contains active login tokens.  Keep it private and never
  commit it to git (it is already covered by .gitignore).
"""

import argparse
import os
import subprocess
import sys
import tempfile
import shutil


# ---------------------------------------------------------------------------
# All domains smutscrape cares about — we run one extraction pass per domain
# so the file stays small and only contains relevant cookies.
# ---------------------------------------------------------------------------
ALL_SMUT_DOMAINS = [
    'xhamster.com',
    'pornhub.com',
    'xvideos.com',
    'xnxx.com',
    'redtube.com',
    'youporn.com',
    'tnaflix.com',
    'motherless.com',
    'incestflix.com',
    'tabootube.xxx',
    'txxx.com',
    'eporner.com',
]

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# Generated by extract_cookies.py for smutscrape / yt-dlp.\n"
    "# DO NOT commit this file to version control.\n"
    "\n"
)


def check_ytdlp():
    if shutil.which('yt-dlp') is None:
        print(
            "[ERROR] yt-dlp not found on PATH.\n"
            "  Install it with:  pip install -U yt-dlp"
        )
        sys.exit(1)


def extract_via_ytdlp(browser, profile, output_path):
    """
    Run yt-dlp once per smutscrape domain to harvest cookies.
    yt-dlp writes a Netscape cookies.txt on its own; we just merge them.

    Strategy:
        yt-dlp --cookies-from-browser chrome \
               --cookies <tmp_file> \
               --skip-download \
               --quiet \
               --no-warnings \
               https://<domain>/

    After each run, append any new lines from tmp_file into the master file.
    """
    browser_arg = browser
    if profile and profile.lower() not in ('default', ''):
        # yt-dlp accepts  "chrome:Profile 1"  syntax
        browser_arg = f"{browser}:{profile}"

    seen_lines = set()
    master_lines = []

    for domain in ALL_SMUT_DOMAINS:
        url = f"https://www.{domain}/"
        with tempfile.NamedTemporaryFile(suffix='.txt', delete=False, mode='w') as tmp:
            tmp_path = tmp.name

        cmd = [
            'yt-dlp',
            '--cookies-from-browser', browser_arg,
            '--cookies', tmp_path,
            '--skip-download',
            '--quiet',
            '--no-warnings',
            url,
        ]

        print(f"[INFO] Extracting cookies for {domain} ...", end=' ', flush=True)
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=30,
            )
        except subprocess.TimeoutExpired:
            print("timeout, skipping.")
            os.unlink(tmp_path)
            continue
        except Exception as e:
            print(f"error ({e}), skipping.")
            os.unlink(tmp_path)
            continue

        # Read whatever yt-dlp wrote
        try:
            with open(tmp_path, 'r', encoding='utf-8', errors='replace') as f:
                raw = f.read()
        except FileNotFoundError:
            print("no output, skipping.")
            continue
        finally:
            try: os.unlink(tmp_path)
            except OSError: pass

        new = 0
        for line in raw.splitlines():
            stripped = line.strip()
            # Skip header/blank lines and duplicates
            if not stripped or stripped.startswith('#'):
                continue
            if stripped not in seen_lines:
                seen_lines.add(stripped)
                master_lines.append(line)
                new += 1

        print(f"{new} new cookies.")

    # Write final file
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(NETSCAPE_HEADER)
        for line in master_lines:
            f.write(line + '\n')

    return len(master_lines)


def parse_args():
    default_out = os.path.join(
        os.path.expanduser('~'), 'smutscrape-cookies.txt'
    )
    p = argparse.ArgumentParser(
        description=(
            'Extract browser cookies to Netscape format for yt-dlp / smutscrape.\n'
            'Uses yt-dlp internally — works on Windows 10/11 without extra packages.'
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        '--output', '-o',
        default=default_out,
        help=f'Output path (default: {default_out})'
    )
    p.add_argument(
        '--browser', '-b',
        default='chrome',
        choices=['chrome', 'chromium', 'brave', 'edge', 'firefox', 'opera', 'vivaldi'],
        help='Browser to extract from (default: chrome)'
    )
    p.add_argument(
        '--profile', '-p',
        default='Default',
        help='Chrome profile name, e.g. "Profile 1" (default: Default)'
    )
    return p.parse_args()


def main():
    args = parse_args()
    check_ytdlp()

    print()
    print(f"Browser : {args.browser}  (profile: {args.profile})")
    print(f"Output  : {args.output}")
    print()

    count = extract_via_ytdlp(args.browser, args.profile, args.output)

    print()
    if count == 0:
        print(
            "[WARN] No cookies were extracted.\n"
            "  Make sure you are logged in to the sites in Chrome\n"
            "  and that yt-dlp can access your browser profile.\n"
            "  On Windows, try closing Chrome first if you see errors."
        )
    else:
        print(f"[OK] {count} unique cookies written to: {args.output}")
        print()
        print("Add this line to your smutscrape config.yaml:")
        # Use forward slashes so YAML doesn't need escaping
        safe_path = args.output.replace('\\', '/')
        print(f'  cookies_file: "{safe_path}"')
        print()
        print("[REMINDER] Keep this file private — never commit it to git.")


if __name__ == '__main__':
    main()
