#!/usr/bin/env python3
"""
extract_cookies.py
==================
Extracts cookies from your browser and writes a Netscape-format cookies.txt
that yt-dlp / smutscrape can consume via the `cookies_file` config key.

Usage (Windows)
-----
    python extract_cookies.py
    python extract_cookies.py --output C:\\Users\\You\\smutscrape-cookies.txt
    python extract_cookies.py --browser edge

Requirements
------------
    yt-dlp must be installed and on PATH:  pip install -U yt-dlp

Notes
-----
- Chrome does NOT need to be closed on Windows.
- The output file contains active login tokens. Keep it private.
- Never commit it to git (already covered by .gitignore).
"""

import argparse
import os
import subprocess
import sys
import tempfile
import shutil


NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# Generated by extract_cookies.py for smutscrape / yt-dlp.\n"
    "# DO NOT commit this file to version control.\n"
    "\n"
)


def check_ytdlp():
    if shutil.which('yt-dlp') is None:
        print(
            "[ERROR] yt-dlp not found on PATH.\n"
            "  Install it with:  pip install -U yt-dlp"
        )
        sys.exit(1)


def validate_output_path(path):
    path = os.path.abspath(path)
    if os.path.isdir(path):
        path = os.path.join(path, 'smutscrape-cookies.txt')
    return path


def extract_via_ytdlp(browser, profile, output_path):
    browser_arg = browser
    if profile and profile.lower() not in ('default', ''):
        browser_arg = f"{browser}:{profile}"

    with tempfile.NamedTemporaryFile(
        suffix='.txt', delete=False, mode='w', encoding='utf-8'
    ) as tmp:
        tmp_path = tmp.name

    cmd = [
        'yt-dlp',
        '--cookies-from-browser', browser_arg,
        '--cookies', tmp_path,
        '--simulate',
        '--ignore-errors',
        'https://xhamster.com/videos/family-12900151',
    ]

    print(f"[INFO] Running: {' '.join(cmd)}")
    print()

    try:
        result = subprocess.run(
            cmd,
            capture_output=False,   # <-- let stdout/stderr print directly to terminal
            text=True,
            timeout=60,
        )
        print()
        print(f"[INFO] yt-dlp exit code: {result.returncode}")
    except subprocess.TimeoutExpired:
        print("[WARN] yt-dlp timed out.")
    except Exception as e:
        print(f"[ERROR] yt-dlp failed: {e}")
        sys.exit(1)

    # Check what was written
    try:
        with open(tmp_path, 'r', encoding='utf-8', errors='replace') as f:
            raw_lines = f.readlines()
        file_size = os.path.getsize(tmp_path)
        print(f"[INFO] Temp cookie file size: {file_size} bytes, {len(raw_lines)} lines")
    except FileNotFoundError:
        print("[ERROR] yt-dlp did not create the cookie file at all.")
        sys.exit(1)
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    cookie_lines = [
        l for l in raw_lines
        if l.strip() and not l.strip().startswith('#')
    ]

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(NETSCAPE_HEADER)
        for line in raw_lines:
            stripped = line.strip()
            if stripped and not stripped.startswith('#'):
                f.write(line if line.endswith('\n') else line + '\n')

    return len(cookie_lines)


def parse_args():
    default_out = os.path.join(os.path.expanduser('~'), 'smutscrape-cookies.txt')
    p = argparse.ArgumentParser(
        description='Extract browser cookies to Netscape format for yt-dlp / smutscrape.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument('--output', '-o', default=default_out,
                   help=f'Output file path (default: {default_out})')
    p.add_argument('--browser', '-b', default='chrome',
                   choices=['chrome', 'chromium', 'brave', 'edge', 'firefox', 'opera', 'vivaldi'],
                   help='Browser to extract from (default: chrome)')
    p.add_argument('--profile', '-p', default='Default',
                   help='Chrome profile name (default: Default)')
    return p.parse_args()


def main():
    args = parse_args()
    check_ytdlp()

    output_path = validate_output_path(args.output)

    print()
    print(f"Browser : {args.browser}  (profile: {args.profile})")
    print(f"Output  : {output_path}")
    print()

    count = extract_via_ytdlp(args.browser, args.profile, output_path)

    print()
    if count == 0:
        print("[WARN] No cookies were written. See yt-dlp output above for the real error.")
    else:
        print(f"[OK] {count} cookies written to: {output_path}")
        safe_path = output_path.replace('\\', '/')
        print()
        print("Add this line to your smutscrape config.yaml:")
        print(f'  cookies_file: "{safe_path}"')
        print()
        print("[REMINDER] Keep this file private \u2014 never commit it to git.")


if __name__ == '__main__':
    main()
