name: FamilyPornHD
domain: familypornhd.com
base_url: "https://familypornhd.com"
selector_style: css
no_overwrite: true
use_selenium: true
m3u8_mode: true
url_encoding_rules:
  " ": "-"
  "%20": "-"

modes:
  video:
    url_pattern: "/{video_id}/"
    scraper: video_scraper
  tag:
    url_pattern: "/tag/{tag}/"
    url_pattern_pages: "/tag/{tag}/page/{page}"
    max_pages: 999
    scraper: list_scraper
  pornstar:
    url_pattern: "/tag/{pornstar}/"
    url_pattern_pages: "/tag/{pornstar}/page/{page}"
    max_pages: 999
    scraper: list_scraper
  search:
    url_pattern: "/?s={search}"
    url_pattern_pages: "/page/{page}/?s={search}"
    max_pages: 999
    scraper: list_scraper
    url_encoding_rules:
      " ": "+"
      "%20": "+"
  studio:
    url_pattern: "/category/{studio}"
    url_pattern_pages: "/category/{studio}/{page}/"
    max_pages: 99
    scraper: list_scraper

download:
  method: "ffmpeg"

scrapers:
  video_scraper:
    title:
      selector: "ol[itemtype='http://schema.org/BreadcrumbList'] li:last-child span[itemprop='name']"
    download_url:
      iframe: "iframe"
    studios:
      selector: "ol[itemtype='http://schema.org/BreadcrumbList'] li:nth-child(2) span[itemprop='name']"
    actors:
      selector: "div.g1-content-narrow p.has-text-align-center a[href*='/tag/']:not(:has(strong))"
    description:
      selector: "div.g1-content-narrow p.has-text-align-center:nth-of-type(2)"
    tags:
      selector: "p.entry-tags a.entry-tag"

  list_scraper:
    video_container:
      selector:
        - "ul.g1-collection-items"
    video_item:
      selector: "li.g1-collection-item article h3.entry-title a"
      fields:
        url:
          attribute: "href"
        title: {}
