name: FamilyPornTV
domain: familyporn.tv
base_url: "https://familyporn.tv"
selector_style: css
no_overwrite: true
use_selenium: true  # Required for video URL extraction

url_encoding_rules:
  " ": "-"
  "%20": "-"

modes:
  video:
    url_pattern: "/videos/{video_id}/"  # Matches "/videos/slug/"
    scraper: video_scraper
  actors:  # Changed from "models" to "actors"
    scraper: list_scraper
    url_pattern: "/models/{actors}/"  # Updated key name reflected in pattern
  category:
    scraper: list_scraper
    url_pattern: "/categories/{category}/"
  search:
    scraper: list_scraper
    url_pattern: "/search/{search}/"

download:
  method: "yt-dlp"  # Already updated as requested

scrapers:
  video_scraper:
    title:
      selector: "head title"  # Kept as is; reliable for now
    download_url:
      selector: "#kt_player > div.fp-player > video"
      attribute: "src"
    studio:  # Changed from "categories" to "studio" (assuming it’s a single entity)
      selector: "div.categories-wrap ul.top-tags li.item a.link span.text:first-child"  # First category as studio
    actors:  # Changed from "models" to "actors"
      selector: "div.video-info div.holder div.item div.star a.link"
    description:
      selector: "div.description div.player-text"
    tags:
      selector: "div.details-tags-wrap ul.details-tags li.item a.link span.text"

  list_scraper:
    video_container:
      selector:
        - "#list_videos_videos_list_search_result_items"
    video_item:
      selector: "li.item > div.thumb-horizontal > a.link"
      fields:
        url:
          attribute: "href"
        title:
          {}
    pagination:
      next_page:
        selector: null  # Pagination via params; no change needed
        attribute: "href"
