name: FamilyPornTV
domain: familyporn.tv
base_url: "https://familyporn.tv"
selector_style: css
no_overwrite: true
use_selenium: true

url_encoding_rules:
  " ": "-"
  "%20": "-"

modes:
  video:
    url_pattern: "/videos/{video_id}/"
    scraper: video_scraper
  model:
    scraper: list_scraper
    url_pattern: "/models/{actors}/"
  category:
    scraper: list_scraper
    url_pattern: "/categories/{category}/"
  search:
    scraper: list_scraper
    url_pattern: "/search/{search}/"
    max_pages: 999
  site:
    scraper: list_scraper
    url_pattern: "/sites/{site}"

download:
  method: "yt-dlp"

scrapers:
  video_scraper:
    title:
      selector: "head title"
    download_url:
      selector: "#kt_player > div.fp-player > video"
      attribute: "src"
    studios:
      selector: "div.categories-wrap ul.top-tags li.item a.link span.text:first-child"
    actors:
      selector: "div.video-info div.holder div.item div.star a.link"
    description:
      selector: "div.description div.player-text"
    tags:
      selector: "div.details-tags-wrap ul.details-tags li.item a.link span.text"

  list_scraper:
    video_container:
      selector:
        - "#list_videos_videos_list_search_result_items"
        - "#list_videos_common_videos_list_items"
    video_item:
      selector: "li.item > div.thumb-horizontal > a.link"
      fields:
        url:
          attribute: "href"
        title:
          {}
    pagination:
      next_page:
        selector: "ul.pagination li.next a.primary-link"
        attribute: "data-parameters"
