name: FamilySex
domain: family-sex.me
base_url: "https://family-sex.me"
selector_style: css
no_overwrite: true
use_selenium: true
url_encoding_rules:
  " ": "-"
  "%20": "-"

modes:
  video:
    url_pattern: "/vids/{video_id}"
    scraper: video_scraper
  tag:
    url_pattern: "/porn/{tag}.html"
    url_pattern_pages: "/porn/{tag}-{page}.html"
    max_pages: 999
    scraper: list_scraper
  search:
    url_pattern: "/search/{search}/"
    scraper: list_scraper
    url_encoding_rules:
      " ": "%20"
      "%20": "%20"

download:
  method: "wget"

scrapers:
  video_scraper:
    title:
      selector: "aside.cvmoplc h1"
    download_url:
      iframe: "div.cvmkesh iframe" # Step 1: Get iframe src (https://ojiz.net/embed/46419)
      selector: "div#kt_player video" # Step 2: Get video src from iframe content
      attribute: "src"
    studios:
      selector: "aside.cvmcaun.cvmtiv a[rel='nofollow']"
    actors:
      selector: "aside.cvmcaun:contains('Starring:') p a"
    description:
      selector: "aside.cvmcaun.cvmoplc.de h2"
    tags:
      selector: "aside.cvmcaun:contains('Related Tags:') p a"
    image:
      selector: "meta[property='og:image']"
      attribute: "content" # Fallback since iframe poster isn’t in static HTML

  list_scraper:
    video_container:
      selector:
        - "div.cvmthumbz"
    video_item:
      selector: "a[target='_self'].v"
      fields:
        url:
          attribute: "href"
        title:
          selector: "img"
          attribute: "alt"
