name: FamilySex
domain: family-sex.me
base_url: "https://family-sex.me"
selector_style: css
no_overwrite: true
use_selenium: true
m3u8_mode: true

url_encoding_rules:
  " ": "-"
  "%20": "-"

modes:
  video:
    url_pattern: "/vids/{video_id}"
    scraper: video_scraper
  tag:
    scraper: list_scraper
    url_pattern: "/porn/{tag}.html"
    url_pattern_pages: "/porn/{tag}-{page}.html"
    max_pages: 999
  search:
    url_pattern: "/search/{search}/"
    scraper: list_scraper

download:
  method: "wget"

scrapers:
  video_scraper:
    title:
      selector: "aside.cvmoplc h1"
    download_url:
      iframe: "iframe"
      selector: "iframe" # Added to extract src
      attribute: "src" # Extracts "https://ojiz.net/embed/46419"
    studios: # Plural for consistency
      selector: "aside.cvmcaun.cvmtiv a[rel='nofollow']"
    actors:
      selector: "aside.cvmcaun:contains('Starring:') p a" # No postProcess
    description:
      selector: "aside.cvmcaun.cvmoplc.de h2"
    tags:
      selector: "aside.cvmcaun:contains('Related Tags:') p a"

  list_scraper:
    video_container:
      selector:
        - "div.cvmthumbz"
    video_item:
      selector: "a[target='_self'].v"
      fields:
        url:
          attribute: "href"
        title:
          selector: "img" # Assuming thumbnail alt or title
          attribute: "alt" # Adjust based on list page HTML
