name: IncestFlix
domain: incestflix.com
base_url: "https://incestflix.com"
selector_style: css
no_overwrite: true

url_encoding_rules:
  " & ": "/and/"
  "&": "/and/"
  " ": "-"
  "%20": "-"

modes:
  video:
    url_pattern: "/watch/{video_id}"
    scraper: video_scraper
  search:
    url_pattern: "/tag/{search}"
    url_pattern_pages: "/tag/{search}/page/{page}"
    max_pages: 999
    scraper: list_scraper
  tag:
    url_pattern: "/tag/{tag}"
    url_pattern_pages: "/tag/{tag}/page/{page}"
    max_pages: 999
    scraper: list_scraper

download:
  method: "curl"

scrapers:
  video_scraper:
    title:
      selector: "div#incflix-videowrap h2"  # From updated, works fine
    download_url:
      selector: "div#incflix-stream source"
      attribute: "src"
    tags:
      selector: "div#videotags a.studiolink3, div#videotags a.studiolink4, div#videotags a.studiolink0"
    actors:
      selector: "div#videotags a.studiolink1"
    studios:
      selector: "div#videotags a.studiolink2"
    image:
      selector: "video#incflix-player"
      attribute: "poster"
      postProcess:
        - replace:
            - regex: "^//"
              with: "http://"  # Fixes protocol-relative URL

  list_scraper:
    video_container:
      selector:
        - "body"
    video_item:
      selector: "a#videolink"
      fields:
        url:
          attribute: "href"
        title:
          selector: "a#videolink"  # Fallback to text if attribute fails
