name: Motherless
domain: motherless.com
base_url: "https://motherless.com"
selector_style: css
no_overwrite: true
use_selenium: true

url_encoding_rules:
  " ": "+"
  "%20": "+"

modes:
  video:
    url_pattern: "/{video}"
    scraper: video_scraper
  search:
    url_pattern: "/search?term={search}&type=videos&range=0&size=0&sort=date"
    url_pattern_pages: "/search?term={search}&type=videos&range=0&size=0&sort=date&page={page}"
    max_pages: 999
    scraper: list_scraper
  category:
    url_pattern: "/porn/{category}/videos"
    url_pattern_pages: "/porn/{category}/videos&page={page}"
    max_pages: 999
    scraper: list_scraper
  user:
    url_pattern: "/u/{user}?t=v"
    url_pattern_pages: "/u/{user}?t=v&page={page}"
    max_pages: 999
    scraper: user_uploads_scraper
  group:
    url_pattern: "/gv/{group}"
    url_pattern_pages: "/gv/{group}?page={page}"
    max_pages: 999
    scraper: group_video_list_scraper

download:
  method: "yt-dlp"

scrapers:
  video_scraper:
    title:
      selector: "head > title"
    download_url:
      selector: "video#ml-main-video_html5_api, #player video"
      attribute: "src"
    tags:
      selector: "div#ml-main-info .more-from-tags a"

  list_scraper:
    video_container:
      selector:
        - ".content-wrapper .content-outer .content-inner"
    video_item:
      selector: ".thumb-container.video .desktop-thumb.video.medium a.img-container"
      fields:
        url:
          attribute: "href"
        title:
          attribute: "title"

  user_uploads_scraper:
    video_container:
      selector:
        - ".content-inner"
    video_item:
      selector: ".thumb-container.video"
      fields:
        url:
          selector: ".desktop-thumb.video.medium a.img-container"
          attribute: "href"
        title:
          selector: ".captions a.caption.title"
          attribute: "title"
        duration:
          selector: ".desktop-thumb.video.medium a.img-container span.size"
        uploader:
          selector: ".caption.left.misc a.uploader"
        views:
          selector: ".caption.left.misc span.hits span.value"

  group_video_list_scraper:
    video_container:
      selector:
        - ".content-inner"
    video_item:
      selector: ".thumb-container.video"
      fields:
        url:
          selector: ".desktop-thumb.video.medium a.img-container"
          attribute: "href"
        title:
          selector: ".captions a.caption.title"
          attribute: "title"
        duration:
          selector: ".desktop-thumb.video.medium a.img-container span.size"
        uploader:
          selector: ".caption.left.misc a.uploader"
        views:
          selector: ".caption.left.misc span.hits span.value"
        group_name:
          selector: ".desktop-thumb.video.medium a.img-container"
          attribute: "href"
          pattern: "/g/([^/]+)/"
