name: Pornhub
domain: pornhub.com
base_url: "https://www.pornhub.com"
selector_style: css
no_overwrite: true
use_selenium: true

url_encoding_rules:
  " ": "-"
  "%20": "-"

modes:
  video:
    url_pattern: "/view_video.php?viewkey={video_id}"
    scraper: video_scraper
  model:
    url_pattern: "/model/{model}/videos"
    scraper: list_scraper
  category:
    url_pattern: "/categories/{category}"
    scraper: list_scraper
  category_alt:
    url_pattern: "/video?c={category_alt}"
    scraper: list_scraper
  channel:
    url_pattern: "/channels/{channel}"
    scraper: list_scraper
  search:
    url_pattern: "/video/search?search={search}"
    scraper: list_scraper
  pornstar:
    url_pattern: "/pornstar/{pornstar}"
    scraper: list_scraper

download:
  method: "yt-dlp"

scrapers:
  video_scraper:
    title:
      selector: "h1"
    download_url:
      selector: "meta[property='og:video']"
      attribute: "content"
    date:
      selector: "script:contains('VideoObject')"
      postProcess:
        - replace:
            - regex: '.*"uploadDate":\s*"([^T]+).*'
              with: "\\1"
        - parseDate: "%Y-%m-%d"
    code:
      selector: "meta[property='og:url']"
      attribute: "content"
      postProcess:
        - replace:
            - regex: ".*viewkey=([^&]+).*"
              with: "\\1"
    tags:
      selector: "div.video-detailed-info a[data-label='category'], div.video-detailed-info a[data-label='tag']"
    actors:
      selector: "div.video-detailed-info a[data-label='pornstar'], div.video-detailed-info span.usernameBadgesWrapper a"
    image:
      selector: "meta[property='og:image']"
      attribute: "content"
    studios:
      selector: "div.videoWrapModelInfo div.usernameWrap a.bolded"

  list_scraper:
    video_container:
      selector:
        - "ul#mostRecentVideosSection"
        - "ul#videoSearchResult"
        - "ul#pornstarsVideoSection"
        - "ul.pornstarsVideos"
        - "ul.mostRecentPornstarVideos"
        - "ul#claimedRecentVideoSection"
        - "ul#moreData"
        - "ul.mostRecentVideosSection"
        - "ul.videos"
        - "ul[class*='videos']"
        - "div.video-wrapper"
    video_item:
      selector: "li.pcVideoListItem"
      fields:
        video_key:
          attribute: "data-video-vkey"
        title:
          selector: "span.title a"
          attribute: "title"
        url:
          selector: "a.linkVideoThumb"
          attribute: "href"
    pagination:
      next_page:
        selector: "li.page_next a"
        attribute: "href"
