# configs/toprealincestvideos.yaml

name: Top Real Incest Videos
shortcode: tr
domain: toprealincestvideos.com
base_url: "https://toprealincestvideos.com"
selector_style: css
no_overwrite: true
use_selenium: false
download:
  method: "yt-dlp"
url_encoding_rules:
  " ": "%20"
note: "Unreliable site that I bothered configuring only because it does host some rare/vintage/homemade content I have not found elsewhere. Among its quirks: no reliable metadata, and search mode doesn't work like you'd expect. Unless you enter the precise searching that corresponds to a category on the site, you'll get no results. Categories can't be directly scraped though, because they have randomized URLs. Also there's no way to go past page 1 of search results."

modes:
  video:
    url_pattern: "/en/video/{video}/"
    scraper: video_scraper
    tip: "Download video with identifier"
    examples:
      - "2705852734797453489"
      - "1892856894654230135"
  search:
    url_pattern: "/en/search/?search={search}"
    scraper: list_scraper
    tip: "Download videos from searching"
    examples:
      - "Father daughter"
      - "Brother sister"
      - "Mother son"
      - "Forced"

scrapers:
  video_scraper:
    title:
      selector: "head title"
    download_url:
      selector: "meta[property='og:video']"
      attribute: "content"

  list_scraper:
    video_container:
      selector:
        - "ul.thumbs-wrapper"
    video_item:
      selector: "li.thumb"
      fields:
        url:
          selector: "a.trd"
          attribute: "href"
        title:
          selector: "p"
    pagination:
      next_page:
        selector: "ul.pages-navigation li.next-prev a:has(i.la-angle-right)"
        attribute: "href"
