name: TopRealIncestVideos
domain: toprealincestvideos.com
base_url: "https://toprealincestvideos.com/en/"
selector_style: css
no_overwrite: true
use_selenium: false

url_encoding_rules:
  " ": "%20"

modes:
  video:
    url_pattern: "/video/{video_id}/"
    scraper: video_scraper
  search:
    url_pattern: "/search/?search={search}"
    scraper: list_scraper
  category:
    url_pattern: "/search/?search={category}"
    scraper: list_scraper

download:
  method: "yt-dlp"

scrapers:
  video_scraper:
    title:
      selector: "head title"
    download_url:
      selector: "meta[property='og:video']"
      attribute: "content"

  list_scraper:
    video_container:
      selector:
        - "ul.thumbs-wrapper"
    video_item:
      selector: "li.thumb"
      fields:
        url:
          selector: "a.trd"
          attribute: "href"
        title:
          selector: "p"
    pagination:
      next_page:
        selector: "ul.pages-navigation li.next-prev a:has(i.la-angle-right)"
        attribute: "href"
