name: XHamster
domain: xhamster.com
base_url: "https://xhamster.com"
selector_style: css
no_overwrite: true
use_selenium: false

url_encoding_rules:
  " ": "-"
  "%20": "-"

modes:
  video:
    url_pattern: "/videos/{video_id}"
    scraper: video_scraper
  pornstar:
    url_pattern: "/pornstar/{pornstar}"
    url_pattern_pages: "/pornstar/{pornstar}/{page}"
    scraper: list_scraper
    max_pages: 999
  search:
    url_pattern: "/search/{search}"
    url_pattern_pages: "/search/{search}?page={page}"
    scraper: list_scraper
    max_pages: 999


download:
  method: "yt-dlp"

scrapers:
  video_scraper:
    title:
      selector: "head title"

  list_scraper:
    video_container:
      selector:
        - "div.thumb-list.thumb-list--sidebar.thumb-list--middle-line"
        - "div.thumb-list.thumb-list--sidebar.thumb-list--middle-line.thumb-list--bigger-with-cube"
    video_item:
      selector: "div.thumb-list__item.video-thumb a.video-thumb__image-container"
      fields:
        url:
          attribute: "href"
        title:
          selector: "a.video-thumb-info__name"
          attribute: "title" 
