name: XHamster
domain: xhamster.com
base_url: "https://xhamster.com"
selector_style: css
no_overwrite: true
use_selenium: false

url_encoding_rules:
  " ": "-"
  "%20": "-"

modes:
  video:
    url_pattern: "/videos/{video_id}"
    scraper: video_scraper
  pornstar:
    url_pattern: "/pornstars/{pornstar}"
    url_pattern_pages: "/pornstars/{pornstar}/{page}"
    scraper: list_scraper
    max_pages: 999
  search:
    url_pattern: "/search/{search}"
    url_pattern_pages: "/search/{search}?page={page}"
    scraper: list_scraper
    max_pages: 999
  category:
    url_pattern: "/categories/{category}"
    url_pattern_pages: "/categories/{category}/{page}"
    scraper: list_scraper
    max_pages: 999

download:
  method: "yt-dlp"

scrapers:
  video_scraper:
    title:
      selector: "head title"
      postProcess:
        - replace:
            - regex: "\\s*\\|\\s*xHamster\\s*"
              with: ""
    tags:
      selector: "div[data-role='video-tags-list'] a.tag-96c3e:not([href*='/pornstars/']):not([href*='/channels/']):not([href*='/users/']) span.label-96c3e"
    actors:
      selector: "div[data-role='video-tags-list'] a.tag-96c3e[href*='/pornstars/'] img.image-9a750"
      attribute: "alt"
    studios:
      selector: "div[data-role='video-tags-list'] a.tag-96c3e[href*='/channels/'] img.image-9a750"
      attribute: "alt"

  list_scraper:
    video_container:
      selector:
        - "div.thumb-list.thumb-list--sidebar.thumb-list--middle-line"
        - "div.thumb-list.thumb-list--sidebar.thumb-list--middle-line.thumb-list--bigger-with-cube"
    video_item:
      selector: "div.thumb-list__item.video-thumb a.video-thumb__image-container"
      fields:
        url:
          attribute: "href"
        title:
          selector: "a.video-thumb-info__name"
          attribute: "title"
