name: XNXX
domain: xnxx.com
base_url: "https://www.xnxx.com"
selector_style: css
no_overwrite: true
use_selenium: true

url_encoding_rules:
  " ": "-"
  "%20": "-"

modes:
  video:
    url_pattern: "/{video_id}/"
    scraper: video_scraper
  search:
    scraper: list_scraper
    url_pattern: "/search/{search}"
    url_pattern_pages: "/search/{search}/{page}"
  channel:
    scraper: list_scraper
    url_pattern: "/channels/{channel}"
    url_pattern_pages: "/channels/{channel}/{page}"
  pornstar:
    scraper: list_scraper
    url_pattern: "/pornstar/{pornstar}"
    url_pattern_pages: "/pornstar/{pornstar}/{page}"
  tag:
    scraper: list_scraper
    url_pattern: "/tags/{tag}"
    url_pattern_pages: "/tags/{tag}/{page}"
  pornmaker:
    scraper: list_scraper
    url_pattern: "/porn-maker/{pornmaker}"
    url_pattern_pages: "/porn-maker/{pornmaker}#_videos,page-{page}"

download:
  method: "yt-dlp"

scrapers:
  video_scraper:
    title:
      selector: "div.video-title strong"
    tags:
      selector: "div.metadata-row.video-tags a.is-keyword"
      postProcess:
        - replace:
            - regex: "Edit tags and models"
              with: ""
    actors:
      selector: "div.metadata-row.video-tags a.is-pornstar"
    studios:
      selector: "span.metadata a.gold-plate, span.metadata a.free-plate"
    description:
      selector: "p.metadata-row.video-description"
      postProcess:
        - replace:
            - regex: "^\\+More videos like this one at .*?\n"
              with: ""
    date:
      selector: "script[type='application/ld+json']"
      postProcess:
        - replace:
            - regex: '.*"uploadDate":\s*"([^"]+)".*'
              with: "\\1"
        - parseDate: "%Y-%m-%dT%H:%M:%S%z"
    image:
      selector: "script:contains('setThumbUrl169')"
      postProcess:
        - replace:
            - regex: ".*setThumbUrl169\\(['\"]([^'\"]+)['\"]\\).*"
              with: "\\1"  # Already fixed

  list_scraper:
    video_container:
      selector:
        - "div#psvideos div.mozaique.cust-nb-cols"
        - "div#content-thumbs div.mozaique.cust-nb-cols"
    video_item:
      selector: "div.thumb-under a"
      fields:
        url:
          attribute: "href"
        title:
          attribute: "title"
    pagination:
      next_page:
        selector: "div.pagination a.next"
        attribute: "href"
