name: XVideos
domain: xvideos.com
base_url: "https://www.xvideos.com"
selector_style: css
no_overwrite: true
use_selenium: false

url_encoding_rules:
  " ": "-"
  "%20": "-"

modes:
  video:
    url_pattern: "{video_id}"
    scraper: video_scraper
  search:
    url_pattern: "/?k={search}"
    scraper: list_scraper
  channel:
    url_pattern: "/channels/{channel}"
    scraper: list_scraper
  model:
    url_pattern: "/models/{model}"
    scraper: list_scraper
  tag:
    url_pattern: "/tags/{tag}"
    scraper: list_scraper

download:
  method: "yt-dlp"

scrapers:
  video_scraper:
    title:
      selector: "head title"

  list_scraper:
    video_container:
      selector:
        - "div.mozaique.cust-nb-cols"
    video_item:
      selector: "div.thumb-under a"
      fields:
        url:
          attribute: "href"
        title:
          selector: "div.thumb-under a"
    pagination:
      next_page:
        selector: "a.page-link.next-page"
        attribute: "href"
